# Site
repository: Falnesio/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Falnésio Ghander Soares Borges
title: Graduado em Ciências Econômicas
titleen: Bachelor of Economics
email: falnesio.ghander@economia.ufjf.br
phone: +55 (33) 9 2000-5046
website: http://bit.do/falnesio 

darkmode: false

# Social links
#twitter_username: none
github_username:  falnesio
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: falnesio
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: UCqFWMjth3RKOqNHwzOUUxqA
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000
telegram_username: falnesio

# Additional icon links
additional_links:
- title: Lattes
  icon: fa-lattes
  url: http://lattes.cnpq.br/8513885038003903
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: img/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Graduado em Ciências Econômicas na Universidade Federal de Juiz de Fora, Campus GV <mark>UFJF - GV</mark> e participa do Núcleo de Agroecologia de Governador Valadares <mark>NAGÔ</mark>. Tem interesse em sistemas complexos. Acredita que modelos que incorporam as sutilezas da heterogeneidade social são úteis na produção de soluções democráticas mais eficazes e eficientes para demandas socioeconômicas e que o estudo econômico tem muito espaço para multidisciplinaridade na formulação de modelos simples mais próximos da realidade. É um pesquisador muito dedicado e focado, é acostumado a entrar em projetos e iniciativas novas, se adaptando aos processos, metodologias e técnicas, aceitando desafios e sempre aprendendo. Trabalha bem em equipe e sempre busca passar o conhecimento que adquiriu para frente.
  
about_content_en: | # this will include new lines to allow paragraphs
  
  Graduado em Ciências Econômicas na Universidade Federal de Juiz de Fora, Campus GV <mark>UFJF - GV</mark> e participa do Núcleo de Agroecologia de Governador Valadares <mark>NAGÔ</mark>. Tem interesse em sistemas complexos. Acredita que modelos que incorporam as sutilezas da heterogeneidade social são úteis na produção de soluções democráticas mais eficazes e eficientes para demandas socioeconômicas e que o estudo econômico tem muito espaço para multidisciplinaridade na formulação de modelos simples mais próximos da realidade. É um pesquisador muito dedicado e focado, é acostumado a entrar em projetos e iniciativas novas, se adaptando aos processos, metodologias e técnicas, aceitando desafios e sempre aprendendo. Trabalha bem em equipe e sempre busca passar o conhecimento que adquiriu para frente.
    
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Linguagem**
    <ul>
       <li>Tradução simultânea EN-PT</li>
       <li>Tradução de texto científico EN-PT</li>
    </ul>  
  **Programação**
    <ul>
       <li>R</li>
       <li>Python</li>
       <li>SQL</li>
    </ul>
  **Tecnologias**
    <ul>
      <li>QGIS</li>
      <li>MySQL</li>
      <li>Microsoft SQL Server</li>
      <li>Microsoft PowerPoint</li>
      <li>Microsoft Excel</li>
      <li>Microsoft Windows</li>
      <li>Microsoft Word</li>
      <li>Microsoft Office</li>
      <li>Ubuntu</li>
      <li>LaTex</li>
    </ul>
  **Habilidades Interpessoais**
    <ul>
      <li>Fazer apresentações</li>
      <li>Lecionar</li>
      <li>Escutar</li>
    </ul>
  **Qualidades Pessoais**
    <ul>
      <li>Autodidata</li>
      <li>Foco</li>
      <li>Paciência</li>
      <li>Dedicação</li>
    </ul>    
    
more_content_en: | # this will include new lines to allow paragraphs
  **Linguagem**
    <ul>
       <li>Tradução simultânea EN-PT</li>
       <li>Tradução de texto científico EN-PT</li>
    </ul>  
  **Programação**
    <ul>
       <li>R</li>
       <li>Python</li>
       <li>SQL</li>
    </ul>
  **Tecnologias**
    <ul>
      <li>QGIS</li>
      <li>MySQL</li>
      <li>Microsoft SQL Server</li>
      <li>Microsoft PowerPoint</li>
      <li>Microsoft Excel</li>
      <li>Microsoft Windows</li>
      <li>Microsoft Word</li>
      <li>Microsoft Office</li>
      <li>Ubuntu</li>
      <li>LaTex</li>
    </ul>
  **Habilidades Interpessoais**
    <ul>
      <li>Fazer apresentações</li>
      <li>Lecionar</li>
      <li>Escutar</li>
    </ul>
  **Qualidades Pessoais**
    <ul>
      <li>Autodidata</li>
      <li>Foco</li>
      <li>Paciência</li>
      <li>Dedicação</li>
    </ul>    
    
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
